### ISSUE TITLE
165: Crash from average_background. Dimension conflicts.

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#194]
**Describe the bug**
When processing certain images, on line 268 of `filters.py`, the dimensions of the image and the array of medians causes a ValueError : operands could not be broadcast together with shapes (512, 1024) (512,).

**To Reproduce**

- python3 topostats/topotracing.py --config config/example.yaml
- Config file (you can attach this or paste it below

```base_dir: C:\Users\Work\OneDrive\Documents\Uni\Research\Data\My_Data\20220215_SmallMinicircles189
output_dir: C:\Users\Work\OneDrive\Documents\Uni\Research\Data\My_Data\20220215_SmallMinicircles189/output
save_plots: true
warnings: ignore
cores: 4
quiet: false
file_ext: .spm
channel: Height
amplify_level: 1.0
filter:
  threshold:
    method: std_dev # 'otsu', 'std_dev', 'absolute'
    otsu_multiplier: 1.7
    std_dev: 0.75
    absolute:
      - 1
      - -1
grains:
  gaussian_size: 2.0
  gaussian_mode: nearest
  absolute_smallest_grain_size: 100
  background: 0.0
  threshold:
    method: otsu # 'otsu', 'std_dev', 'absolute'
    otsu_multiplier: 1.7
    std_dev: 1.0
    absolute:
      - 1
      - -1
```

**Expected behavior**
This error should not arise, the subtraction should be completed, with each line of the image being lowered by the average height of the image.

**Output**
```
[Thu, 07 Jul 2022 12:54:04] [INFO    ] [topostats] saved grain image: 32
[Thu, 07 Jul 2022 12:54:04] [INFO    ] [topostats] [20220215_189bp_DNA_minicircles_3mM.0_00012] : Row and column medians calculated.
[Thu, 07 Jul 2022 12:54:04] [INFO    ] [topostats] [20220215_189bp_DNA_minicircles_3mM.0_00012] : Zero averaging background
Processing images from C:\Users\Work\OneDrive\Documents\Uni\Research\Data\My_Data\20220215_SmallMinicircles189, results
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Work\anaconda3\envs\TopoStatsPy3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Work\OneDrive\Documents\Uni\Research\Code\TopoStatsCode\topostats\topotracing.py", line 190, in process_scan
    filtered_image.filter_image()
  File "c:\users\work\onedrive\documents\uni\research\code\topostatscode\topostats\filters.py", line 313, in filter_image
    self.images["zero_averaged_background"] = self.average_background(
  File "c:\users\work\onedrive\documents\uni\research\code\topostatscode\topostats\filters.py", line 268, in average_background
    return image - np.array(medians["rows"], ndmin=1).T
ValueError: operands could not be broadcast together with shapes (512,1024) (512,)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./topostats/topotracing.py", line 300, in <module>
    main()
  File "./topostats/topotracing.py", line 295, in main
    for _ in pool.imap_unordered(processing_function, img_files):
  File "C:\Users\Work\anaconda3\envs\TopoStatsPy3\lib\multiprocessing\pool.py", line 868, in next
    raise value
ValueError: operands could not be broadcast together with shapes (512,1024) (512,)
```

**(Not required if using Docker) Your computer configuration (please complete the following information):**
 - OS: Windows
 - topostats version: Branch: 165-improve-thresholding-methods, commit: c9ffdf1091a85202a7751c843cec0d04866bdfc5
 - Python version: 3.8

**Comment by SylviaWhittle** [comment]
Cannot reproduce and the code for `average_background` has since been completely replaced with new code, so closing.
