### ISSUE TITLE
Use bounding boxes linked to the threshold layer.

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#207]
**Describe the bug**

Recently the ability to apply an `upper` and `lower` threshold to grain finding was introduced when using a threshold method of `std_dev` (which is scaled by a given factor and `-/+` from the mean to give the thresholds). Unfortunately bounding boxes from the `upper` layer are overlaid .

**To Reproduce**

Ensure the following options are set...

```yaml
...
filter:
  ...
  threshold:
    method: std_dev
    ...
    std_dev: 1.5
    ...
grains:
  ...
  threshold:
    method: std_dev
    ...
    std_dev: 1.5
```

Then run against the `dev` branch.

```bash
git checkout dev
run_topostats <path_to_yaml>
```

**Expected behavior**

Bounding boxes should cover grains found on that layer.

**Output**

![image](https://user-images.githubusercontent.com/17566406/178476475-3d94bcd9-554c-4989-9edb-7534588de0b7.png)

These are the bounding boxes from the `upper` layer, only one grain is found in the `lower` layer and is coloured red here and does not have a bounding box.

Fails with the following...

```bash
 ❱ run_topostats -c example-std-dev.yaml
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Configuration file loaded from      : example-std-dev.yaml
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Scanning for images in              : .
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Output directory                    : output-std-dev
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Looking for images with extension   : .spm
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Images with extension .spm in . : 1
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Thresholding method (Filtering)     : std_dev
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Thresholding method (Grains)        : std_dev
Processing images from ., results are under output-std-dev:   0%|                                                                                            | 0/1 [00:00<?, ?it/s][Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Processing : minicircle.spm
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Extracting filename from : minicircle.spm
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Filename : minicircle
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Loading image from : minicircle.spm
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Loaded image from : minicircle.spm
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Extracting filename from : minicircle.spm
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] Loading image from : minicircle.spm
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Loaded image from : minicircle.spm
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Created directory : output-std-dev/minicircle/filters/minicircle
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Extracted channel Height Sensor
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Pixels extracted
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Pixels to nm scaling : 0.4940029296875
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Masking disabled
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Median Row Height: 142.6841223471669
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Rows aligned
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Masking disabled
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] X-gradient: 5.551115123125783e-17
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] Y-gradient: 0.0029161773506112265
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : X/Y tilt removed
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Masking (upper) Threshold: 142.1092189172997
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Masking (lower) Threshold: 140.34187554623668
[Tue, 12 Jul 2022 12:12:20] [INFO    ] [topostats] [minicircle] : Masking enabled
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Median Row Height: 141.09713447797583
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Rows aligned
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Masking enabled
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] X-gradient: 0.0
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] Y-gradient: 1.7883317175670932e-05
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : X/Y tilt removed
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Masking enabled
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Zero averaging background
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Grain Finding
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Thresholding method (grains) : std_dev
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Applying Gaussian filter (mode : nearest; Gaussian blur (nm) : 2.0).
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Masking (lower) Threshold: -0.7445334393695139
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Tidying borders
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Removing noise (< 100)
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Labelling Regions
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Region properties calculated
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Labelling Regions
[Tue, 12 Jul 2022 12:12:21] [INFO    ] [topostats] [minicircle] : Region properties calculated
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Coloured regions
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Extracting bounding boxes
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Applying Gaussian filter (mode : nearest; Gaussian blur (nm) : 2.0).
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Masking (upper) Threshold: 1.0248891043823307
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Tidying borders
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Removing noise (< 100)
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Labelling Regions
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Region properties calculated
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : No grains found.
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Grain Statistics
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Grain statistics saved to output-std-dev/minicircle/lower/grainstats.csv
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Errors occurred attempting to calculate grain statistics and DNA tracing statistics.
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Plotting Filtering Images
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/00-raw_heightmap.png
[Tue, 12 Jul 2022 12:12:22] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/01-pixels.png
[Tue, 12 Jul 2022 12:12:23] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/02-initial_align_unmasked.png
[Tue, 12 Jul 2022 12:12:23] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/03-initial_tilt_removal_unmasked.png
[Tue, 12 Jul 2022 12:12:23] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/05-secondary_align_masked.png
[Tue, 12 Jul 2022 12:12:24] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/06-secondary_tilt_removal_masked.png
[Tue, 12 Jul 2022 12:12:24] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/07-zero_average_background.png
[Tue, 12 Jul 2022 12:12:24] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/04-binary_mask.png
[Tue, 12 Jul 2022 12:12:24] [INFO    ] [topostats] [minicircle] : Plotting Grain Images
[Tue, 12 Jul 2022 12:12:24] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/08-gaussian_filtered.png
[Tue, 12 Jul 2022 12:12:24] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/lower/09-mask_grains.png
[Tue, 12 Jul 2022 12:12:25] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/lower/10-tidy_borders.png
[Tue, 12 Jul 2022 12:12:25] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/lower/11-noise_removed.png
[Tue, 12 Jul 2022 12:12:25] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/lower/12-labelled_regions.png
[Tue, 12 Jul 2022 12:12:25] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/lower/13-small_objects_removed.png
[Tue, 12 Jul 2022 12:12:25] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/lower/14-labelled_regions.png
[Tue, 12 Jul 2022 12:12:25] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/lower/15-coloured_regions.png
[Tue, 12 Jul 2022 12:12:25] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/lower/16-bounding_boxes.png
[Tue, 12 Jul 2022 12:12:25] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/lower/17-labelled_image_bboxes.png
[Tue, 12 Jul 2022 12:12:26] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/upper/09-mask_grains.png
[Tue, 12 Jul 2022 12:12:26] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/upper/10-tidy_borders.png
[Tue, 12 Jul 2022 12:12:26] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/upper/11-noise_removed.png
[Tue, 12 Jul 2022 12:12:26] [INFO    ] [topostats] [minicircle] : Image saved to : output-std-dev/minicircle/upper/12-labelled_regions.png
Processing images from ., results are under output-std-dev:   0%|                                                                                            | 0/1 [00:06<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/neil/work/projects/topostats/TopoStats/topostats/run_topostats.py", line 336, in process_scan
    grains.directions[direction]["coloured_regions"],
KeyError: 'coloured_regions'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/neil/.virtualenvs/topostats/bin/run_topostats", line 33, in <module>
    sys.exit(load_entry_point('topostats', 'console_scripts', 'run_topostats')())
  File "/home/neil/work/projects/topostats/TopoStats/topostats/run_topostats.py", line 413, in main
    for img, result in pool.imap_unordered(processing_function, img_files):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
KeyError: 'coloured_regions'
```

**Comment by ns-rse** [comment]
#208 resolves this
