### ISSUE TITLE
Dev: run_topostats fails

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#296]
**Describe the bug**
Running the run_topostats command as standalone crashes due to a mismatch between configuration files. I know what the error is and will fix it imminently. 

**To Reproduce**

- Run run_topostats in the terminal as standard.

**Expected behavior**
Not a crash.

**Output**

```
(virtual_env) sylvi@Sylvias-MacBook-Pro TopoStats % run_topostats
default config loaded: {'base_dir': './', 'output_dir': './output', 'warnings': 'ignore', 'cores': 4, 'quiet': False, 'file_ext': '.spm', 'filter': {'run': True, 'channel': 'Height', 'amplify_level': 1.0, 'threshold_method': 'std_dev', 'otsu_threshold_multiplier': 1.0, 'threshold_std_dev': 1.0, 'threshold_absolute_lower': -1.0, 'threshold_absolute_upper': 1.0}, 'grains': {'run': True, 'gaussian_size': 2.0, 'gaussian_mode': 'nearest', 'absolute_smallest_grain_size': 100, 'threshold_method': 'std_dev', 'otsu_threshold_multiplier': 1.0, 'threshold_std_dev': 1.0, 'threshold_absolute_lower': -1.0, 'threshold_absolute_upper': 1.0, 'direction': 'upper', 'background': 0.0}, 'grainstats': {'run': True, 'cropped_size': 40, 'save_cropped_grains': True}, 'dnatracing': {'run': True}, 'plotting': {'run': True, 'save_format': 'png', 'image_set': 'core', 'zrange': [0, 3], 'colorbar': True, 'axes': True, 'cmap': 'nanoscope'}}
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Configuration file loaded from      : None
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Scanning for images in              : /Users/sylvi/Documents/GitKraken/TopoStats
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Output directory                    : output
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Looking for images with extension   : .spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Images with extension .spm in /Users/sylvi/Documents/GitKraken/TopoStats : 2
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Thresholding method (Filtering)     : std_dev
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Thresholding method (Grains)        : std_dev
Processing images from /Users/sylvi/Documents/GitKraken/TopoStats, results are under output:   0%|       | 0/2 [00:00<?, ?it/s][Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Processing : /Users/sylvi/Documents/GitKraken/TopoStats/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Extracting filename from : /Users/sylvi/Documents/GitKraken/TopoStats/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Filename : minicircle
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Loading image from : /Users/sylvi/Documents/GitKraken/TopoStats/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Processing : /Users/sylvi/Documents/GitKraken/TopoStats/tests/resources/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Extracting filename from : /Users/sylvi/Documents/GitKraken/TopoStats/tests/resources/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Filename : minicircle
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Loading image from : /Users/sylvi/Documents/GitKraken/TopoStats/tests/resources/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Loaded image from : /Users/sylvi/Documents/GitKraken/TopoStats/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Extracting filename from : /Users/sylvi/Documents/GitKraken/TopoStats/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Loading image from : /Users/sylvi/Documents/GitKraken/TopoStats/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Loaded image from : /Users/sylvi/Documents/GitKraken/TopoStats/tests/resources/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Extracting filename from : /Users/sylvi/Documents/GitKraken/TopoStats/tests/resources/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] Loading image from : /Users/sylvi/Documents/GitKraken/TopoStats/tests/resources/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Loaded image from : /Users/sylvi/Documents/GitKraken/TopoStats/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Created directory : output/Processed
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Loaded image from : /Users/sylvi/Documents/GitKraken/TopoStats/tests/resources/minicircle.spm
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Created directory : output/tests/resources/Processed
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Extracted channel Height
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Extracted channel Height
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Pixels extracted
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Pixels to nm scaling : 0.4940029296875
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Pixels extracted
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Pixels to nm scaling : 0.4940029296875
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Masking disabled
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Masking disabled
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Median Row Height: 29.29087487488389
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Median Row Height: 29.29087487488389
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Rows aligned
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Rows aligned
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Masking disabled
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Masking disabled
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : X-gradient: 0.0
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Y-gradient: 0.003159027190419463
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : X-gradient: 0.0
[Mon, 26 Sep 2022 15:31:20] [INFO    ] [topostats] [minicircle] : Y-gradient: 0.003159027190419463
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : X/Y tilt removed
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : X/Y tilt removed
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Masking (upper) Threshold: 28.382985321353974
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Masking (upper) Threshold: 28.382985321353974
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Masking (lower) Threshold: 27.045051324866566
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Masking (lower) Threshold: 27.045051324866566
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Masking enabled
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Masking enabled
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Median Row Height: 27.588853247948727
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Median Row Height: 27.588853247948727
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Rows aligned
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Rows aligned
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Masking enabled
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Masking enabled
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : X-gradient: 0.0
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Y-gradient: -5.783605658230689e-06
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : X-gradient: 0.0
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Y-gradient: -5.783605658230689e-06
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : X/Y tilt removed
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Masking enabled
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : X/Y tilt removed
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Masking enabled
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Zero averaging background
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Applying Gaussian filter (mode : nearest; Gaussian blur (nm) : None).
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Row and column medians calculated.
[Mon, 26 Sep 2022 15:31:21] [INFO    ] [topostats] [minicircle] : Zero averaging background
Processing images from /Users/sylvi/Documents/GitKraken/TopoStats, results are under output:   0%|       | 0/2 [00:01<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/run_topostats.py", line 185, in process_scan
    filtered_image.filter_image()
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/filters.py", line 369, in filter_image
    self.images["gaussian_filtered"] = self.gaussian_filter(self.images["zero_averaged_background"])
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/filters.py", line 322, in gaussian_filter
    sigma=(self.gaussian_size / self.pixel_to_nm_scaling),
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sylvi/Documents/GitKraken/TopoStats/virtual_env/bin/run_topostats", line 8, in <module>
    sys.exit(main())
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/run_topostats.py", line 411, in main
    for img, result in pool.imap_unordered(processing_function, img_files):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**(Not required if using Docker) Your computer configuration (please complete the following information):**
- MacOS (OSX)

**Comment by ns-rse** [comment]
Closed by #297
