### ISSUE TITLE
Topostats crashes when a file without a set channel is found

### ISSUE THREAD

**Issue by derollins** [AFM-SPM/TopoStats#582]
**NB** TopoStats `< 2.0.0` is no longer actively maintained. If you have encountered an issue using this deprecated
version please try TopoStats `>= 2.0.0`, there are instructions on
[installation](https://afm-spm.github.io/TopoStats/installation.html),
[usage](https://afm-spm.github.io/TopoStats/usage.html) and
[configuration](https://afm-spm.github.io/TopoStats/configuration.html).

By default TopoStats will process images in parallel to speed up processing. In order to identify the problematic image
you should re-run your analyses using the `--cores 1` option so that images are processed sequentially. This makes it
possible to identify which image causes the problem.

## Checklist

Please try and tick off each of these items when filing the bug report. There are further instructions on each below.

* [X] Re-run analysis with `run_topostats --core 1`.
* [X] Describe the bug.
* [X] Include the configuration file.
* [X] Copy of the output.
* [X] The exact command that failed. This is what you typed at the command line, including any options.
* [X] TopoStats version, this is reported by `run_topostats --version`
* [X] Operating System and Python Version

## Describe the bug

Nanoscope produces lots of data types with the same .spm file extension including non-image data such as force curves. When one of these is present in a folder that topostats is processing the programme crashes.

Would be great if it could just skip these files instead.

## Copy of the output

Please copy and paste the output that is shown below within the `\`` (triple-backticks).

``` [Tue, 23 May 2023 10:43:18] [INFO    ] [topostats] Extracting image from E:\Users\Eddie ROLLINS\20210511_DNA_Minicircles\20210511_DNA_Minicircles0_00020.0_00074.spm
[Tue, 23 May 2023 10:43:18] [INFO    ] [topostats] Loading image from : E:\Users\Eddie ROLLINS\20210511_DNA_Minicircles\20210511_DNA_Minicircles0_00020.0_00074.spm
[Tue, 23 May 2023 10:43:18] [INFO    ] [topostats] [20210511_DNA_Minicircles0_00020.0_00074] : Loaded image from : E:\Users\Eddie ROLLINS\20210511_DNA_Minicircles\20210511_DNA_Minicircles0_00020.0_00074.spm
[Tue, 23 May 2023 10:43:18] [ERROR   ] [topostats] [20210511_DNA_Minicircles0_00020.0_00074] : Height not in .spm channel list: []
[Tue, 23 May 2023 10:43:18] [ERROR   ] [topostats] [io.py] [401] [20210511_DNA_Minicircles0_00020.0_00074] : Height not in .spm channel list: []
Traceback (most recent call last):
  File "C:\Users\NanoScope\.conda\envs\topostats_pypi\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NanoScope\.conda\envs\topostats_pypi\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\NanoScope\.conda\envs\topostats_pypi\Scripts\run_topostats.exe\__main__.py", line 7, in <module>
  File "C:\Users\NanoScope\.conda\envs\topostats_pypi\lib\site-packages\topostats\run_topostats.py", line 226, in main
    all_scan_data.get_data()
  File "C:\Users\NanoScope\.conda\envs\topostats_pypi\lib\site-packages\topostats\io.py", line 752, in get_data
    self.image, self.pixel_to_nm_scaling = suffix_to_loader[suffix]()
  File "C:\Users\NanoScope\.conda\envs\topostats_pypi\lib\site-packages\topostats\io.py", line 388, in load_spm
    self.channel_data = scan.get_channel(self.channel)
  File "C:\Users\NanoScope\.conda\envs\topostats_pypi\lib\site-packages\pySPM\Bruker.py", line 155, in get_channel
    return self.get_channel(channel=channel,backward=not backward, corr=corr, debug=debug, encoding=encoding, lazy=False)
  File "C:\Users\NanoScope\.conda\envs\topostats_pypi\lib\site-packages\pySPM\Bruker.py", line 156, in get_channel
    raise Exception("Channel {} not found".format(channel))
Exception: Channel Height not found
```

## Include the configuration file

If no configuration file was specified with the `-c`/`--config-file` option the defaults were used, please use the
`run_topostats --create-config-file crash.yaml` to save these to the `crash.yaml` file and copy the contents below.

``` # Sample configuration file auto-generated : 2023-05-23 10:31:32
# For more information on configuration : https://afm-spm.github.io/TopoStats/main/configuration.html
base_dir: E:\Users\Eddie ROLLINS
output_dir: E:\Users\Eddie ROLLINS/output
log_level: info
cores: 1
file_ext: .spm
loading:
  channel: Height
filter:
  run: true
  row_alignment_quantile: 0.5
  threshold_method: std_dev
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    below: 10.0
    above: 1.0
  threshold_absolute:
    below: -1.0
    above: 1.0
  gaussian_size: 1.0121397464510862
  gaussian_mode: nearest
  remove_scars:
    run: true
    removal_iterations: 2
    threshold_low: 0.25
    threshold_high: 0.666
    max_scar_width: 4
    min_scar_length: 16
grains:
  run: true
  threshold_method: std_dev
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    below: 10.0
    above: 1.0
  threshold_absolute:
    below: -1.0
    above: 1.0
  direction: above
  smallest_grain_size_nm2: 50
  absolute_area_threshold:
    above:
    - 300
    - 3000
    below:
    - 
    - 
grainstats:
  run: true
  edge_detection_method: binary_erosion
  cropped_size: 40.0
dnatracing:
  run: false
  min_skeleton_size: 10
plotting:
  run: true
  save_format: png
  pixel_interpolation:
  image_set: core
  zrange:
  - -4
  - 4
  colorbar: true
  axes: true
  cmap: nanoscope
  mask_cmap: blu
  histogram_log_axis: false
  histogram_bins: 200
  dpi: 300
summary_stats:
  run: true
  config:

```

## To Reproduce

If it is possible to share the file (e.g. via cloud services) that caused the error that would greatly assist in
reproducing and investigating the problem. In addition the _exact_ command used that failed should be pasted below.
https://drive.google.com/file/d/15oSUqrq3eY9xNLDkOfXVA0GCDdn3KqPx/view?usp=share_link
``` 
run_topstats -c eddie_config.yaml
```

## Output

Any output files that have been produced can be attached to this bug report (by default they will be under the `output`
directory unless you have customised the configuration).

## TopoStats version

Please report the version of TopoStats you are using. There are several ways of doing this, either with `pip` or
`run_topostats`. Please copy and paste all output from either of the following commands.

* `pip show topostats`
* `run_topostats --version`

``` 
Installed version of TopoStats : 2.1.0
```

### Operating System

Please let us know what operating system you are using, if you have used more than one then tick all boxes.

* [X] Windows
* [ ] MacOS Intel (pre-2021)
* [ ] MacOS M1/M2 (post-2021)
* [ ] GNU/Linux (please include distribution)

### Python Version

Please let us know the version of Python you are using, paste the results of `python --version`

``` 
Python 3.10.11
```

**Comment by derollins** [comment]
Also to note is if the data has a 'height sensor' channel rather than 'height' it appears in errors and other spm analysis software as 'z sensor'. This makes knowing what to put in the channel field difficult to determine.
