### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#686]
Add support and CI pipelines for Python 3.12 which was [released 2023-10-02](https://docs.python.org/3.12/whatsnew/3.12.html).

**Comment by ns-rse** [comment]
Initial attempt under a Conda environment with Python 3.12.0 gives....

```bash
pip install -e .[tests]
...
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/neil/miniconda3/envs/python312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/neil/miniconda3/envs/python312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/neil/miniconda3/envs/python312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/home/neil/miniconda3/envs/python312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/neil/miniconda3/envs/python312/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-1ftutcd2/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-1ftutcd2/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-1ftutcd2/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

A quick search [suggested](https://pythontest.com/posts/2023/2023-10-02-py312-impimporter/) its down to `pip`/`virtualenv` caching packages so tried with the `--no-cache-dir` option to `pip` but hit the same

**Comment by ns-rse** [comment]
Progress...

## `scikit-image`

`scikit-image` on which we depend throws...

```bash
❱ pytest
ImportError while loading conftest '/home/neil/work/git/hub/AFM-SPM/TopoStats/tests/conftest.py'.
tests/conftest.py:13: in <module>
    from topostats.grainstats import GrainStats
topostats/grainstats.py:12: in <module>
    import skimage.feature as skimage_feature
/home/neil/miniconda3/envs/topo312/lib/python3.12/site-packages/skimage/feature/__init__.py:11: in <module>
    from .corner import (corner_kitchen_rosenfeld, corner_harris,
/home/neil/miniconda3/envs/topo312/lib/python3.12/site-packages/skimage/feature/corner.py:13: in <module>
    from ._hessian_det_appx import _hessian_matrix_det
E   ImportError: /home/neil/miniconda3/envs/topo312/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/neil/miniconda3/envs/topo312/lib/python3.12/site-packages/skimage/feature/_hessian_det_appx.cpython-312-x86_64-linux-gnu.so)
```

Python 3.12 is [supported as there are wheels built](https://github.com/scikit-image/scikit-image/issues/7149).

In my Conda environment I have `libstdcxx-ng-11.2.0` and `libgcc-ng-11.2.0` installed.

Upgrading to `scikit-image-0.22.0` resolved this but that conflicts with the requirements for pyspm...

```bash

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyspm 0.4.0 requires scikit-image<0.22.0,>=0.21.0, but you have scikit-image 0.22.0 which is incompatible.
Successfully installed scikit-image-0.22.0
```

...and I now only have the `igor2` issue cropping up.

I've made a [pull request](https://github.com/scholi/pySPM/pull/36) to relax the `scikit-image` dependency in `pyspm`.


## `igor2`

```bash
❱ topostats
zsh: correct 'topostats' to 'TopoStats' [nyae]? n
Traceback (most recent call last):
  File "/home/neil/miniconda3/envs/topo312/bin/topostats", line 5, in <module>
    from topostats.entry_point import entry_point
  File "/home/neil/work/git/hub/AFM-SPM/TopoStats/topostats/entry_point.py", line 10, in <module>
    from topostats.plotting import run_toposum
  File "/home/neil/work/git/hub/AFM-SPM/TopoStats/topostats/plotting.py", line 15, in <module>
    from topostats.io import read_yaml, save_pkl, write_yaml, convert_basename_to_relative_paths
  File "/home/neil/work/git/hub/AFM-SPM/TopoStats/topostats/io.py", line 18, in <module>
    from igor2 import binarywave
  File "/home/neil/miniconda3/envs/topo312/lib/python3.12/site-packages/igor2/__init__.py", line 5, in <module>
    from . import binarywave
  File "/home/neil/miniconda3/envs/topo312/lib/python3.12/site-packages/igor2/binarywave.py", line 114, in <module>
    BinHeader1 = _Structure(  # `version` field pulled out into Wave
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Struct() takes at most 1 keyword argument (2 given)
```

This has stumped me and I can't work out what is going on here so have raised an [issue for igor2 maintainers](https://github.com/AFM-analysis/igor2/issues/9).

**Comment by ns-rse** [comment]
[PR](https://github.com/scholi/pySPM/pull/36) on `pySPM` has been merged so its just the AFM-analysis/igor2/issues/9 that we're waiting. If/when resolved we can test TopoStats tests against Python 3.12 again.
