### ISSUE TITLE
DeprecationWarning: Pickle, copy, and deepcopy support will be removed from itertools in Python 3.14.

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#869]
Currently seeing a deprecation warning when processing...
```
Traceback (most recent call last):
  File "/home/neil/.virtualenvs/topostats/bin/topostats", line 8, in <module>
    sys.exit(entry_point())
             ^^^^^^^^^^^^^
  File "/home/neil/work/git/hub/AFM-SPM/TopoStats/topostats/entry_point.py", line 386, in entry_point
    args.func(args)
  File "/home/neil/work/git/hub/AFM-SPM/TopoStats/topostats/run_topostats.py", line 199, in run_topostats
    toposum(summary_config)
  File "/home/neil/work/git/hub/AFM-SPM/TopoStats/topostats/plotting.py", line 411, in toposum
    save_pkl(outfile=outfile, to_pkl=figures)
  File "/home/neil/work/git/hub/AFM-SPM/TopoStats/topostats/io.py", line 1226, in save_pkl
    pkl.dump(to_pkl, f)
DeprecationWarning: Pickle, copy, and deepcopy support will be removed from itertools in Python 3.14.
```

## `python --version`

```
 ❱ python --version
Python 3.12.4
```

## `pip show topostats`

```
 ❱ pip show topostats
Name: topostats
Version: 2.2.2.dev5+gf5b40f762
Summary: Automated Analysis for Atomic Force Microscopy Images of Biomolecules
Home-page: 
Author: 
Author-email: TopoStats Team <topostats@sheffield.ac.uk>, Alice Pyne <a.l.pyne@sheffield.ac.uk>, Sylvia Whittle <sylvia.whittle@sheffield.ac.uk>, Neil Shephard <n.shephard@sheffield.ac.uk>, Max Gamill <mcgamill1@sheffield.ac.uk>, Jean Du <mdu12@sheffield.ac.uk>
License: GNU Lesser GPLv3 only
Location: /home/neil/.virtualenvs/topostats/lib/python3.12/site-packages
Editable project location: /home/neil/work/git/hub/AFM-SPM/TopoStats
Requires: AFMReader, h5py, igor2, matplotlib, numpy, pandas, pyfiglet, pySPM, pyyaml, ruamel.yaml, schema, scikit-image, scipy, seaborn, snoop, tifffile, tqdm
Required-by: 

## `pip freeze`

Not Applicable this is an issue with `itertools` which is a standard library.

**Comment by ns-rse** [comment]
If no one uses the saved pickles we should remove support/functionality and simplify our code base.
