### ISSUE TITLE
ResourceWarning: unclosed file <_io.TextIOWrapper name='./TopoStats-2024-07-04-18-25-53.log' mode='a' encoding='UTF-8'>

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#870]
Seeing this exception/warning whenever running `topostats <command>` (including `create-config`)...

```
 ❱ topostats process -c config.yaml
Exception ignored in: <_io.FileIO name='/home/neil/work/git/hub/AFM-SPM/TopoStats/TopoStats-2024-07-04-18-25-53.log' mode='ab' closefd=True>
Traceback (most recent call last):
  File "/home/neil/work/git/hub/AFM-SPM/TopoStats/topostats/statistics.py", line 8, in <module>
    LOGGER = setup_logger(LOGGER_NAME)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/neil/work/git/hub/AFM-SPM/TopoStats/TopoStats-2024-07-04-18-25-53.log' mode='a' encoding='UTF-8'>
Exception ignored in: <_io.FileIO name='/home/neil/work/git/hub/AFM-SPM/TopoStats/TopoStats-2024-07-04-18-25-53.log' mode='ab' closefd=True>
Traceback (most recent call last):
  File "/home/neil/work/git/hub/AFM-SPM/TopoStats/topostats/processing.py", line 31, in <module>
    LOGGER = setup_logger(LOGGER_NAME)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/neil/work/git/hub/AFM-SPM/TopoStats/TopoStats-2024-07-04-18-25-53.log' mode='a' encoding='UTF-8'>
```

## `python --version`

```
 ❱ python --version
Python 3.12.4
```

## `pip show topostats`

```
 ❱ pip show topostats
Name: topostats
Version: 2.2.2.dev5+gf5b40f762
Summary: Automated Analysis for Atomic Force Microscopy Images of Biomolecules
Home-page: 
Author: 
Author-email: TopoStats Team <topostats@sheffield.ac.uk>, Alice Pyne <a.l.pyne@sheffield.ac.uk>, Sylvia Whittle <sylvia.whittle@sheffield.ac.uk>, Neil Shephard <n.shephard@sheffield.ac.uk>, Max Gamill <mcgamill1@sheffield.ac.uk>, Jean Du <mdu12@sheffield.ac.uk>
License: GNU Lesser GPLv3 only
Location: /home/neil/.virtualenvs/topostats/lib/python3.12/site-packages
Editable project location: /home/neil/work/git/hub/AFM-SPM/TopoStats
Requires: AFMReader, h5py, igor2, matplotlib, numpy, pandas, pyfiglet, pySPM, pyyaml, ruamel.yaml, schema, scikit-image, scipy, seaborn, snoop, tifffile, tqdm
Required-by: 

## `pip freeze`

Not Applicable (I don't think) as this is an issue with `logging` which is a standard library.

**Comment by MaxGamill-Sheffield** [comment]
I think I fixed this in #976 which removes multiple loggers from being created :)
